Gadget_Galaxy/Gadget_Galaxy/urls.py
from django.contrib import admin
from django.urls import path
from product.views import *
from category.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/<id>/',pro_list,name='pro_list'),
    path('category/<id>/', cat_list, name='cat_list'),

]

category/urls.py
from django.urls import path
from . import views
from .views import (
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
)
app_name = 'category'

urlpatterns = [
    path('', views.category_list, name='category_list'),
    path('create/', views.category_create, name='create'),
    path('edit/<int:pk>/', views.category_edit, name='edit'),
    path('delete/<int:pk>/', views.category_delete, name='delete'),
    
    path('gv', CategoryListView.as_view(), name='category_list'),
    path('createg/', CategoryCreateView.as_view(), name='create'),
    path('editg/<int:pk>/', CategoryUpdateView.as_view(), name='edit'),
    path('deleteg/<int:pk>/', CategoryDeleteView.as_view(), name='delete'),
]

ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('product.urls')),
    path('admin/', admin.site.urls),
    path('category/', include('category.urls')),  
    path('product/', include('product.urls')),
    path('accounts/', include('accounts.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path,include
from . import views
from .views import ProductListView
from .views import ProductDeleteView
from .api.views import *
from rest_framework.routers import DefaultRouter


app_name = 'product'
router = DefaultRouter()
router.register(r'API', ProductViewSet, basename='product')


urlpatterns = [
    path('', include(router.urls)),
]


# urlpatterns = [
#     #api gi based
#     path('API/', ProductListCreateAPIView.as_view(), name='product-list-create'),
#     path('API/<int:pk>/', ProductDetailAPIView.as_view(), name='product-detail'),
#     #api class based
#     path('API/<int:pk>/', ProductUpdateAPIView.as_view(), name='product-update'),
#     #api function based
#     path('API/<int:id>',getbyid,name='getbyid'),
#     path('API/',getallpro,name='getallpro'),



#     path('plistview', ProductListView.as_view(), name='product_list'),
#     path('', views.product_list, name='product_list'),
#     path('create/', views.product_create, name='create'),
#     path('create_fm/', views.product_create_MF, name='create'),
#     path('edit/<int:pk>/', views.product_edit, name='edit'),
#     path('edit_f/<int:pk>/', views.product_edit, name='edit'),
#     # path('delete/<int:pk>/', views.product_delete, name='delete'),
#     path('classdelete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
# ]

Gadget_Galaxy/product/models.py
from django.db import models

class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100,null=True)
    slug = models.CharField(max_length=100,null=True)
    description = models.CharField(max_length=9000,null=True)
    price = models.DecimalField(max_digits=10,decimal_places=2,null=True)
    stock = models.IntegerField(null=True)
    sku = models.CharField(max_length=100,null=True)

product/models.py
from django.db import models
from category.models import Category
from django.utils.text import slugify
from django.urls import reverse



class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product/imgs', blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    status=models.BooleanField(default=True)


    @classmethod
    def getall(cls):
        return cls.objects.filter(status=True)
    
    @classmethod
    def get_by_id(cls,id):
        return cls.objects.get(pk=id)
       
    @classmethod
    def harddel(cls,id):
        return cls.objects.filter(pk=id).delete()
    
    @classmethod
    def softdelete(cls,id):
        Product.objects.filter(pk=id).update(
            status=False
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:product_detail', args=[self.id, self.slug])
    













    # @classmethod
    # def Add(cls,name,pdate,image,catagoryid):
    #     catagoryobj = Catagory2.get_catagory_by_id(catagoryid)
    #     # create object of book model
    #     Book2.objects.create(name=name,
    #                          publish_date=pdate,
    #                          image=image,
    #                          catagory=catagoryobj)
    
    # @classmethod
    # def update(cls,id,name,publish_date,catagory):
    #     # #update
    #     Book2.objects.filter(pk=id).update(
    #         name=name,
    #         publish_date=publish_date,
    #         # image=req.FILES['Bimage'],
    #         catagory=Catagory2.get_catagory_by_id(id)
    #     )
 

product/forms.py
# product/forms.py
from django import forms
from .models import *
from category.models import Category
from django.shortcuts import get_object_or_404


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'category', 'image']



class ProductFormHandler:
    @staticmethod
    def handle_edit_form(request, product):
        product.name = request.POST.get('name')
        product.description = request.POST.get('description')
        product.price = request.POST.get('price')
        product.category = get_object_or_404(Category, pk=request.POST.get('category'))
        
        if 'image' in request.FILES:
            product.image = request.FILES['image']
        
        product.save()
        return product

Gadget_Galaxy/product/views.py
from django.shortcuts import render
from django.http.response import HttpResponse

def pro_list(requset, id):
    objrepo = HttpResponse()
    objrepo.write(f'<h1>Product {id}</h1>')
    return objrepo

product/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status,viewsets
from django.shortcuts import get_object_or_404
from .serlizer import ProductSerlizer
from ..models import Product
from rest_framework.views import APIView
from rest_framework import generics



class ProductViewSet(viewsets.ViewSet):
    
    def list(self, request):
        products = Product.getall()
        serializer = ProductSerlizer(products, many=True)
        return Response(serializer.data)
    
    def create(self, request):
        serializer = ProductSerlizer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def retrieve(self, request, pk=None):
        product = get_object_or_404(Product, pk=pk)
        serializer = ProductSerlizer(product)
        return Response(serializer.data)
    
    def update(self, request, pk=None):
        product = get_object_or_404(Product, pk=pk)
        serializer = ProductSerlizer(product, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def partial_update(self, request, pk=None):
        """Partial update of a product"""
        product = get_object_or_404(Product, pk=pk)
        serializer = ProductSerlizer(product, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def destroy(self, request, pk=None):
        product = get_object_or_404(Product, pk=pk)
        product.softdelete(pk)
        return Response(status=status.HTTP_204_NO_CONTENT)


class ProductDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerlizer
    lookup_field = 'pk'

    def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        instance.softdelete()
        return Response(
            {"message": "Product deleted successfully"},
            status=status.HTTP_204_NO_CONTENT
        )

class ProductListCreateAPIView(generics.ListCreateAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerlizer


class ProductUpdateAPIView(APIView):
    def put(self, request, pk):
        try:
            product = get_object_or_404(Product, pk=pk)
            serializer = ProductSerlizer(product, data=request.data)
            
            if serializer.is_valid():
                serializer.save()
                return Response(
                    {"message": "Product updated successfully"},
                    status=status.HTTP_200_OK
                )
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        except Exception as e:
            return Response(
                {"error": str(e)},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR
            )

    # Add this to handle PATCH requests as well if needed
    def patch(self, request, pk):
        return self.put(request, pk)




@api_view(['GET', 'DELETE'])
def getbyid(request, id):
    product = get_object_or_404(Product, pk=id)

    if request.method == 'GET':
        serialized = ProductSerlizer(product)
        return Response(serialized.data, status=status.HTTP_200_OK)

    elif request.method == 'DELETE':
        try:
            product.softdelete(id) 
            return Response({"message": "Product deleted successfully"}, status=status.HTTP_204_NO_CONTENT)
        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'POST'])  
def getallpro(request):
    if request.method == 'GET':
        products = Product.getall()
        P_After_serializer = ProductSerlizer(products, many=True)
        return Response(P_After_serializer.data, status=status.HTTP_200_OK)
    
    elif request.method == 'POST':
        print("Request data:", request.data)
        serializer = ProductSerlizer(data=request.data)
        if serializer.is_valid():
            print("Serializer is valid. Saving...")
            serializer.save()
            return Response(serializer.data, status=201)
        else:
            print("Serializer errors:", serializer.errors) 
            return Response(serializer.errors, status=400)
    

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product
from .forms import ProductForm
from category.models import Category
from .forms import ProductFormHandler 
from django.views.generic import ListView
from django.views.generic import DeleteView
from django.urls import reverse_lazy



class ProductListView(ListView):
    model = Product
    template_name = 'product/list.html'
    context_object_name = 'products'  
    
    def get_queryset(self):
        return Product.getall() 


def product_list(request):
    products = Product.getall()
    
    return render(request, 'product/list.html', {'products': products})


def product_create_MF(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid() and form.is_bound:
            form.save()
            return redirect('product:product_list')
    else:
        form = ProductForm()
    
    return render(request, 'product/create_mf.html', {'form': form})


def product_create(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        category = get_object_or_404(Category, pk=request.POST.get('category'))
        product = Product(
            name=request.POST.get('name'),
            description=request.POST.get('description'),
            price=request.POST.get('price'),
            category=category
        )
        if 'image' in request.FILES:
            product.image = request.FILES['image']
        product.save()
        return redirect('product:product_list')
    return render(request, 'product/create.html', {'categories': categories})



def product_edit(request, pk):
    product = get_object_or_404(Product, pk=pk)
    categories = Category.objects.all()
    if request.method == 'POST':
        product.name = request.POST.get('name')
        product.description = request.POST.get('description')
        product.price = request.POST.get('price')
        product.category = get_object_or_404(Category, pk=request.POST.get('category'))
        
        if 'image' in request.FILES:
            product.image = request.FILES['image']
            
        product.save()
        return redirect('product:product_list')
    return render(request, 'product/edit.html', {'product': product, 'categories': categories})




def product_edit_f(request, pk):
    product = get_object_or_404(Product, pk=pk)
    categories = Category.objects.all()
    
    if request.method == 'POST':
        ProductFormHandler.handle_edit_form(request, product)
        return redirect('product:product_list')
    
    return render(request, 'product/edit.html', {
        'product': product,
        'categories': categories
    })


def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.softdelete(pk)
    return redirect('product:product_list') 


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('product:product_list') 
    
    def delete(self, request, *args, **kwargs):

        self.object = self.get_object()
        self.object.softdelete()
        return redirect(self.get_success_url())

product/templates/product/create.html
{% extends "base.html" %}
{% block title %}Add product{% endblock %}
{% block content %}
<h1>Create New Product</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label>Name:</label>
        <input type="text" name="name" required>
    </div>
    <div class="form-group">
        <label>Description:</label>
        <textarea name="description"></textarea>
    </div>
    <div class="form-group">
        <label>Price:</label>
        <input type="number" name="price" step="0.01" required>
    </div>
    <div class="form-group">
        <label>Category:</label>
        <select name="category" required>
            {% for category in categories %}
            <option value="{{ category.pk }}">{{ category.name }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label>Product Image:</label>
        <input type="file" name="image" accept="image/*">
    </div>

    <button type="submit" class="btn">Save</button>
    <a href="{% url 'product:product_list' %}" class="btn btn-danger">Cancel</a>
</form>
{% endblock %}

product/templates/product/create_mf.html
<!-- product/create.html -->
{% extends "base.html" %}

{% block content %}
<h1>Create New Product</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn">Save</button>
    <a href="{% url 'product:product_list' %}" class="btn btn-danger">Cancel</a>
</form>
{% endblock %}

product/templates/product/detail.html
{% extends "base.html" %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
    <h1>{{ product.name }}</h1>
    <p>Category: <a href="{{ product.category.get_absolute_url }}">{{ product.category.name }}</a></p>
    <img src="{% if product.image %}{{ product.image.url }}{% endif %}" alt="{{ product.name }}" width="300">
    <p>{{ product.description }}</p>
    <p>Price: ${{ product.price }}</p>
    <p>Added: {{ product.date_added }}</p>
{% endblock %}

product/templates/product/edit.html
{% extends "base.html" %}
{% load static %}

{% block title %}Edit Product - {{ product.name }}{% endblock %}

{% block content %}
{% block extra_css %}
<style>
    main{
        height: 100%;
    }
</style>
{%endblock%}
<div class="container">
    <h1>Edit Product</h1>
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="name">Product Name:</label>
            <input type="text" id="name" name="name" value="{{ product.name }}" class="form-control" required>
        </div>
        
        <div class="form-group">
            <label for="description">Description:</label>
            <textarea id="description" name="description" class="form-control" rows="4" required>{{ product.description }}</textarea>
        </div>
        
        <div class="form-group">
            <label for="price">Price:</label>
            <input type="number" id="price" name="price" value="{{ product.price }}" step="0.01" class="form-control" required>
        </div>
        
        <div class="form-group">
            <label for="category">Category:</label>
            <select id="category" name="category" class="form-control" required>
                {% for category in categories %}
                    <option value="{{ category.pk }}" {% if category.pk == product.category.pk %}selected{% endif %}>
                        {{ category.name }}
                    </option>
                {% endfor %}
            </select>
        </div>
        
        <div class="form-group">
            <label for="image">Product Image:</label>
            <input type="file" id="image" name="image" class="form-control-file">
            {% if product.image %}
                <div class="mt-2">
                    <img src="{{ product.image.url }}" alt="{{ product.name }}" style="max-height: 200px;">
                </div>
            {% endif %}
        </div>
        
        
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Save Changes</button>
            <a href="{% url 'product:product_list' %}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

product/templates/product/list.html
{% extends "base.html" %}
{% block title %}Products{% endblock %}
{% block content %}
<h1>Products</h1>
<a href="{% url 'product:create' %}" class="btn">Add New Product</a>

<table class="crud-table">
    <thead>
        <tr>
            <th>Image</th>
            <th>Name</th>
            <th>Category</th>
            <th>Price</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for product in products %}
        <tr>
            <td>
                {% if product.image %}
                <img src="{{ product.image.url }}" alt="{{ product.name }}" style="max-height: 50px;">
                {% else %}
                <div style="width:50px; height:50px; background:#eee; display:inline-block;"></div>
                {% endif %}
            </td>
            <td>{{ product.name }}</td>
            <td>{{ product.category.name }}</td>
            <td>${{ product.price }}</td>
            <td class="actions">
                <a href="{% url 'product:edit' product.pk %}" class="btn">Edit</a>
                <form method="post" action="{% url 'product:delete' product.pk %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}