Gadget_Galaxy/Gadget_Galaxy/urls.py
from django.contrib import admin
from django.urls import path
from product.views import *
from category.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/<id>/',pro_list,name='pro_list'),
    path('category/<id>/', cat_list, name='cat_list'),

]

accounts/urls.py
from django.urls import path
from .views import register_view, login_view, logout_view

app_name = 'accounts'

urlpatterns = [
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

category/urls.py
from django.urls import path
from . import views
from .views import (
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
)
app_name = 'category'

urlpatterns = [
    path('', views.category_list, name='category_list'),
    path('create/', views.category_create, name='create'),
    path('edit/<int:pk>/', views.category_edit, name='edit'),
    path('delete/<int:pk>/', views.category_delete, name='delete'),
    
    path('gv', CategoryListView.as_view(), name='category_list'),
    path('createg/', CategoryCreateView.as_view(), name='create'),
    path('editg/<int:pk>/', CategoryUpdateView.as_view(), name='edit'),
    path('deleteg/<int:pk>/', CategoryDeleteView.as_view(), name='delete'),
]

ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('product.urls')),
    path('admin/', admin.site.urls),
    path('category/', include('category.urls')),  
    path('product/', include('product.urls')),
    path('accounts/', include('accounts.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from category.models import Category
from django.utils.text import slugify
from django.urls import reverse



class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product/imgs', blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    status=models.BooleanField(default=True)


    @classmethod
    def getall(cls):
        return cls.objects.filter(status=True)
    
    @classmethod
    def get_by_id(cls,id):
        return cls.objects.get(pk=id)
       
    @classmethod
    def harddel(cls,id):
        return cls.objects.filter(pk=id).delete()
    
    @classmethod
    def softdelete(cls,id):
        Product.objects.filter(pk=id).update(
            status=False
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:product_detail', args=[self.id, self.slug])
    













    # @classmethod
    # def Add(cls,name,pdate,image,catagoryid):
    #     catagoryobj = Catagory2.get_catagory_by_id(catagoryid)
    #     # create object of book model
    #     Book2.objects.create(name=name,
    #                          publish_date=pdate,
    #                          image=image,
    #                          catagory=catagoryobj)
    
    # @classmethod
    # def update(cls,id,name,publish_date,catagory):
    #     # #update
    #     Book2.objects.filter(pk=id).update(
    #         name=name,
    #         publish_date=publish_date,
    #         # image=req.FILES['Bimage'],
    #         catagory=Catagory2.get_catagory_by_id(id)
    #     )
 

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gadget Galaxy - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
    <header class="main-header">
        <div class="container">
            <h1><a href="/">Gadget Galaxy</a></h1>
            <nav class="main-nav">
                <ul>
                    <li><a href="{% url 'accounts:login' %}">Login/register</a></li>
                    <li><a href="{% url 'category:category_list' %}">Categories</a></li>
                    <li><a href="{% url 'product:product_list' %}">Products</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <main class="container">
        {% block content %}{% endblock %}
    </main>

    <footer class="main-footer">
        <div class="container">
            <p>&copy; 2023 Gadget Galaxy. All rights reserved.</p>
        </div>
    </footer>
</body>
</html>